Change the name of the biomes and add a basis to the corrupted vinesword
Team-Cryptic-Cosmos/Cryptic-Cosmos pull request #12
Opened 2020-11-22 06:39 UTC by DenDragon23

2020-11-22 17:32 UTC, xf8b requested changes
formatting issues, other than that looks good

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/LovecraftPlus.java
> +        RenderTypeLookup.setRenderLayer(BlockRegistries.CORRUPTED_VINESWORD.get(),RenderType.getCutout());
reformat to add a space between commas

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/blocks/CorruptedVinesword.java
> +public class CorruptedVinesword extends FlowerBlock {
should sword be capitalized?

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/registries/BlockRegistries.java
> +            5, Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0F).sound(SoundType.PLANT)));
please reformat to make this less confusing

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/MondroveGroveBiome.java
> +        super.addSpawn(type, spawnListEntry);
useless method

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +
remove empty new line

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +    public static final BlockClusterFeatureConfig VINESWORD_CONFIG = (new BlockClusterFeatureConfig.Builder((new WeightedBlockStateProvider()).addWeightedBlockstate(VINESWORD, 2), new SimpleBlockPlac
remove useless parentheses, format so that this isnt so long

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +        this.addFeature(GenerationStage.Decoration.VEGETAL_DECORATION, Feature.RANDOM_RANDOM_SELECTOR.withConfiguration(new MultipleWithChanceRandomFeatureConfig(ImmutableList.of(Feature.RANDOM_PATCH
reformat so this isnt so long

2020-11-22 17:32 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +        super.addSpawn(type, spawnListEntry);
useless method

2020-11-22 17:35 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/LovecraftPlus.java
> +        RenderTypeLookup.setRenderLayer(BlockRegistries.CORRUPTED_VINESWORD.get(),RenderType.getCutout());
```suggestion
        RenderTypeLookup.setRenderLayer(BlockRegistries.CORRUPTED_VINESWORD.get(), RenderType.getCutout());
```

2020-11-22 17:36 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/registries/BlockRegistries.java
> +            5, Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0F).sound(SoundType.PLANT)));
```suggestion
            5, Properties.create(Material.PLANTS)
            .doesNotBlockMovement()
            .hardnessAndResistance(0.0F)
            .sound(SoundType.PLANT))
        );
```

2020-11-22 17:36 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/registries/BlockRegistries.java
> +            5, Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0F).sound(SoundType.PLANT)));
er wait github formattting is bad

2020-11-22 17:38 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +
```suggestion
```

2020-11-22 17:39 UTC, TheOnlyTails commented on src/main/java/com/github/hauntedchest/lovecraftplus/blocks/CorruptedVinesword.java
> +public class CorruptedVinesword extends FlowerBlock {
I don't think so.

2020-11-22 17:39 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/blocks/CorruptedVinesword.java
> +public class CorruptedVinesword extends FlowerBlock {
mm ok

2020-11-22 17:41 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/MondroveGroveBiome.java
> +        super.addSpawn(type, spawnListEntry);
er nevermind, forgot that the super method is protected

2020-11-22 17:41 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +        super.addSpawn(type, spawnListEntry);
super method is protected, ignore this

2020-11-22 20:22 UTC, xf8b requested changes
more changes

2020-11-22 20:22 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/registries/BlockRegistries.java
> +            5, Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0F).sound(SoundType.PLANT)));
please reformat to make this less confusing

2020-11-22 20:22 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +    public static final BlockClusterFeatureConfig VINESWORD_CONFIG = (new BlockClusterFeatureConfig.Builder((new WeightedBlockStateProvider()).addWeightedBlockstate(VINESWORD, 2), new SimpleBlockPlac
make this less longer

2020-11-22 20:22 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +    public static final BlockClusterFeatureConfig VINESWORD_CONFIG = (new BlockClusterFeatureConfig.Builder((new WeightedBlockStateProvider()).addWeightedBlockstate(VINESWORD, 2), new SimpleBlockPlac
also, i think you broke this because of your latest change

2020-11-22 20:22 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +        this.addFeature(GenerationStage.Decoration.VEGETAL_DECORATION,
this should be on a new line

2020-11-22 20:22 UTC, xf8b commented on src/main/java/com/github/hauntedchest/lovecraftplus/world/biomes/VulvonPlainsBiome.java
> +                        (new MultipleWithChanceRandomFeatureConfig(ImmutableList.of
your formatting makes this very confusing

2020-11-23 06:03 UTC, TheOnlyTails reviewed
Looks good. Just add all of xf8b's requested changes.

2020-11-27 01:56 UTC, xf8b commented
this has not seen any activity for 4 days

2020-11-27 01:57 UTC, DenDragon23 commented
> this has not seen any activity for 4 days

Yeah, I am busy, you can work on it.

2020-11-27 01:58 UTC, xf8b commented
> > this has not seen any activity for 4 days
> 
> Yeah, I am busy, you can work on it.
ok

2020-11-27 01:58 UTC, DenDragon23 commented
> > > this has not seen any activity for 4 days
> > 
> > 
> > Yeah, I am busy, you can work on it.
> > ok

can you?

2020-11-27 01:59 UTC, xf8b commented
well yes but actually no, since github suggestions are not very good for java code

2020-11-27 02:00 UTC, DenDragon23 commented
but can't you work on the branch itself? I need to do some other shtuff

2020-11-27 02:02 UTC, xf8b commented
right, thought this was a fork lmao

sure, i'll clone it in a bit gimme a sec

2020-11-27 04:40 UTC, xf8b commented
smh past me what have you done

2020-12-31 04:25 UTC, xf8b commented
smh past me what have you done

2021-02-02 07:29 UTC, TheOnlyTails commented
Outdated.

2021-02-02 07:29 UTC, closed without merging