Revamp blocks
Team-Cryptic-Cosmos/Cryptic-Cosmos pull request #36
Opened 2021-02-07 04:46 UTC by HauntedChest13

I remade all of the blocks and textures! Also added some

2021-02-07 06:46 UTC, TheOnlyTails requested changes
Change all the stuff I talked about, and please fix the overgrown lunon item model.
Also, if you change stuff like that, make sure to update the moon pillars NBT.

2021-02-07 06:46 UTC, TheOnlyTails commented on src/main/java/com/crypticcosmos/crypticcosmos/registries/BlockRegistries.java
>              () -> new Block(Properties.create(Material.ROCK)
If you're using the same properties for every lunon variant, just make it in one place (like regular lunon), and use `Properties.of` to use it everywhere else.

2021-02-07 06:46 UTC, TheOnlyTails commented on src/main/java/com/crypticcosmos/crypticcosmos/datagen/RecipesGenerator.java
> +    private void registerLUNONRecipes(Consumer<IFinishedRecipe> consumer) {
Oops! make sure to check your search and replace didn't change anything unexpected!

2021-02-07 06:46 UTC, TheOnlyTails commented on src/main/java/com/crypticcosmos/crypticcosmos/datagen/RecipesGenerator.java
> +        // LUNON bricks
same here!

2021-02-07 06:48 UTC, TheOnlyTails commented
Closes #36

2021-02-07 06:51 UTC, TheOnlyTails commented
Also, can you remove the unused blocks and items in this PR?

2021-02-07 08:10 UTC, TheOnlyTails requested changes
You need to change the contents of the file too.

2021-02-07 08:20 UTC, HauntedChest13 commented
I did and it works, I checked in game.

2021-02-08 08:37 UTC, TheOnlyTails reviewed
Looks good! I'll check everything works and approve.

2021-02-08 08:56 UTC, TheOnlyTails approved these changes
Everything is working perfectly! Time to merge!

2021-02-08 08:56 UTC, merged