Removed important changed type of lambda
Team-Cryptic-Cosmos/Cryptic-Cosmos pull request #54
Opened 2021-04-24 05:09 UTC by KingRealzYT

Removed important changed type of lambda

2021-04-24 20:46 UTC, TheOnlyTails requested changes
LGTM, just change the parameter name.

2021-04-24 20:46 UTC, TheOnlyTails commented on src/main/java/com/crypticcosmos/crypticcosmos/registries/StrippingRegistries.java
> +                        event.getItemStack().hurtAndBreak(1, playerEntity, (p_220040_1_) -> p_220040_1_.broadcastBreakEvent(event.getHand()));
Can you please use something other than the unmapped name and remove the unnecessary parentheses?

2021-04-24 21:03 UTC, KingRealzYT commented on src/main/java/com/crypticcosmos/crypticcosmos/registries/StrippingRegistries.java
> +                        event.getItemStack().hurtAndBreak(1, playerEntity, (p_220040_1_) -> p_220040_1_.broadcastBreakEvent(event.getHand()));
yea sure

2021-04-25 13:25 UTC, TheOnlyTails approved these changes
LGTM!

2021-04-25 13:25 UTC, merged